steps:
# Step 0
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          docker build -t europe-west1-docker.pkg.dev/linear-encoder-424111-i7/api/divehub:$COMMIT_SHA .
          docker push europe-west1-docker.pkg.dev/linear-encoder-424111-i7/api/divehub:$COMMIT_SHA


  # Step 2 - Deploy the image in a Cloud Run service

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        - 'run'
        - 'deploy'
        - 'divehub'
        - '--image'
        - 'europe-west1-docker.pkg.dev/linear-encoder-424111-i7/api/divehub:$COMMIT_SHA'
        - '--region'
        - 'europe-west1'
        - '--platform'
        - 'managed'
        - '--port'
        - '8080'
        - '--allow-unauthenticated'

